//汉化杂项
var cnItems = {
    'skills': '技能',
    'sliders': '滑块',
    'Power': '力量',
    'Spirit': '精神',
    'Unknown': '未知',
    'None': '无',
    'Low load mode': '低负载模式',
    'Master gilding touch control': '掌握镀金触摸控制',
    'Gilding touch': '镀金触摸',
    'Master imbuement control': '掌握灌输控制',
    'Safe': '安全',
    'Hide completed': '隐藏已完成',
    'Hide enchanted': '隐藏魔法',
    'Hide imprinted/unimprintable': '隐藏印记/不可打印',
    'Mining': '采矿',
    'No damage': '无伤害',
    'Attacking': '攻击',
    'Free': '空闲',
    'Target connected if possible': '如果有可能，连接目标',
    'Master channel control': '掌握通道控制',
    'Elemental summons avoid same element': '元素召唤避免相同的元素',
    'Distribute equally on change': '变化均匀分布',
    'Re-sort upon change': '改变后重新排序',
    'Research this': '研究这个',
    'Summons avoid narrow path': '避免狭窄路径',
    'Redistribute if exceeding total': '如果超过总数，重新分配',
    'Main story display': '主要故事显示',
    'Off': '关闭',
    'On': '开启',
    'Side story display': '侧面故事显示',
    'Story timing': '故事时间',
    'Highest damage': '最高伤害',
    'Deepest': '最大深度',
    'Farthest': '距离最远',
    'Closest': '距离最近',
    'Most defended': '最高防御',
    'Least defended': '最低防御',
    'Strongest': '最强输出',
    'Random': '随机',
    'Always': '经常',
    '30 minutes': '30分钟',
    '10 minutes': '10分钟',
    '5 minute': '5分钟',
    '1 minute': '1分钟',
    '1 hour': '1小时',
    'Least deep': '最小深度',
    'Weakest': '最弱输出',
    'Leader': '领导者',
    'Follower': '追随者',
    'Low load mode only': '仅低负载模式',
    '15 seconds': '15秒',
    'Autosave period': '自动保存周期',
    'From Map tab only': '只从地图选项卡',
    'From any tab': '从任何选项卡',
    'Node size scale': '缩放尺寸',
    'Maximum level': '最高等级',
    'Sort by': '排序',
    'Level': '等级',
    'Growth': '成长',
    'Depth': '深度',
    'Gold': '黄金',
    'Mana': '法术',
    'Science': '科学',
    'Focus': '焦点',
    'Blood': '血',
    'Fire': '火',
    'Ice': '冰',
    'Metal': '金属',
    'Short number format': '短数字格式',
    'Natural': '标准',
    'Scientific': '科学计数法',
    'Engineering': '工程符号',
    'Scientific number display': '科学数字显示',
    'Upper bound for full numbers': '上限为完整的数字',
    'Lower bound for full numbers': '下限为完整的数字',
    'Precision of short numbers': '简短数字的精确性',
    'Color theme': '主题颜色',
    'Light': '白灰',
    'Dark': '暗黑',
    'Distribute for equal growth on change': '分配平等的增长变化',
    'Invert lightness': '反转亮度',
    'Color blind mode': '色盲模式',
    'Artifact icons': '物品图标',
    'Text': '文字',
    'Images': '图片',
    'Rough ETA display': '粗略估计显示',
    'Numbers': '数字',
    'Fireworks': '烟花效果',
    'Miner/worker sparks': '矿工/工人火花',
    'Display dead zones': '显示死亡区域',
    'Display connectable distance': '显示连接距离',
    'Allow detached node placement': '允许分离节点的位置',
    'Mechanics guide display': '力学指南显示',
    'Game time': '游戏时间',
    'Ten times per second': '每秒10次',
    'Thirty times per second': '每秒30次',
    'Once per second': '每秒1次',
    'Once per five seconds': '每5秒1次',
    'Automatic low load mode when not active window': '当没有活动窗口时，自动进入低负载模式',
    'Node level display': '节点等级显示',
    'Number': '数字',
    'Show': '显示',
    'Hide': '隐藏',
    'Fade': '淡出',
    'Circles': '圆圈',
    'Uncaptured node lines': '未捕捉到的节点线',
    'Solid': '实线',
    '5 minutes': '5分钟',
    'Popup': '弹出框',
    'Log': '日志',
    'Lightning effects': '闪电效果',
    'Show overriden controls': '显示重载控制',
    'Show growth controls (available by click if hidden)': '显示增长控件(如果隐藏，点击显示)',
    'Cloud save period': '云端储存期',
    'Autoload cloud save if newer one found': '如果找到云存档，则自动加载云存档',
    'Hiberload': '休眠负载',
    'Target': '目标',
    'World time': '世界时间',
    'Game processing speed': '游戏处理速度',
    'Slow mode processing speed': '慢速模式处理速度',
    'Automatic low load mode when idling': '空转时自动进入低负载模式',
    'Display map progress while in automatic low load mode': '在自动低负载模式下显示地图进度',
    'Upload cloud saves if logged in': '如果登录了，上传云端保存',
    'Captured node notification': '捕获节点通知',
    'Role': '角色',
    'Lowest solo ETA': '最低solo ETA',
    'Dashed': '虚线',
    'Red': '红色',
    'Green': '绿色',
    'Blue': '蓝色',
    'Exp': '经验',
    'Experience': '经验',
    'Stars': '星星',
    'Stardust': '星尘',
    'Resources': '资源',
    'Main window': '主窗口',
    'Map tab': '地图标签页',
    'Node information': '节点信息',
    'Node specials': '节点特点',
    'Controls': '控制',
    'Ascension': '转生',
    "This is game's main window. You can see the map you are exploring and order your sliders around.": '这是游戏的主窗口。 您可以看到您正在探索的地图并调整滑块。',
    'Power: This number determines how strong the node is. Most of other values depend on this one.': '功率：此数字决定节点的强度。 大多数其他值取决于此值。',
    'This list displays accumulated growth speed of your sliders, supported by nodes you have captured. Every second your sliders gain increase in displayed attrubites unless some other mechanics alter the change.': '此列表显示滑块的累积增长速度，并由您捕获的节点支持。除非有其他机制改变改变，否则你的滑块显示的属性的数量会增加。',
    'Namely, "Exp <-> Growth" sliders allow you to convert some of this growth to Experience.': '也就是说 “经验 < - > 增长”滑条允许你将这些增长转化为经验。',
    'Growth control': '成长控制',
    'Autotargetting': '自动定位',
    'Sliders tab': '滑块选项卡',
    'While any kind of autotargetting is enabled, slider will check for new available target every time a node is captured on a map.': '当任何一种自动定位启动时，滑块每次在地图上捕捉到一个节点时就会检查新的目标。',
    'You can set up a lot of different autotargetting rules with some of them unlocked over time with separate skills.': '您可以设置许多不同的自动定位规则，其中一些规则可以随着时间的推移通过不同的技能解除锁定。',
    "In this tab you can control your sliders, which are your main means of advancing through the game. You can change slider's displayed color by double-clicking its header.": '在这个选项卡中，你可以控制你的滑块，这是你在游戏中前进的主要方式。您可以通过双击滑块的标题来更改其显示的颜色。',
    'By adjusting Exp<->Growth sliders, you can set up, how much of growth will be applied to given attribute of given slider, and how much is converted into Experience.': '通过调整 经验<->增长 滑块，您可以设置，有多少增长将应用于给定滑块的给定属性，有多少转换为经验。',
    'Skills tab': '技能选项卡',
    'You can obtain new skills here. Most skills require experience to obtain. Experience cost multiplier is applier to every cost, and obtaining a skill makes every other skill more expensive. ': '你可以在这里获得新的技能。大多数技能需要经验来获得。经验成本倍增器适用于每一种成本，而获得一种技能会使其他技能变得更加昂贵。',
    'New skills can be unlocked by acsending, obtaining more sliders, discovering new resources and other means.': '可以通过转生、获取更多的滑块、发现新的资源和其他方法来解锁新技能。',
    'Rough ETA: The approximate node capture time based on current damage. Can be very unreliable, especially early on.': '粗略估计，根据目前的伤害，大致估计节点的捕获时间。可能非常不可靠，尤其是在早期。',
    'Saves': '保存',
    'Sounds': '声音',
    'World': '世界',
    'Story': '故事',
    'Performance': '性能',
    'Display': '显示',
    'Map': '地图',
    'Online time': '在线时间',
    'Offline time': '离线时间',
    'Found stars': '找到星星',
    'Captured points': '捕获点数',
    'Points up to level 1': '指向1级',
    'Points up to level 2': '指向2级',
    'Points up to level 3': '指向3级',
    'Points up to level 4': '指向4级',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

};

function cnItem(text) {
    //数组里面有的，返回中文
    for (var i in cnItems) {
        if (text == i) {
            return cnItems[i];
        }
    }
    //数组里面没有的，原样返回
    for (var i in cnItems) {
        if (text != i) {
            console.log("需汉化的英文Item：" + text);
            return text;
        }
    }
}



//汉化标题
var cntit = {
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    

};

function cntitle(text) {
    //数组里面有的，返回中文
    for (var i in cntit) {
        if (text == i) {
            return cntit[i];
        }
    }
    //数组里面没有的，原样返回
    for (var i in cntit) {
        if (text != i) {
            console.log("需汉化的英文标题：" + text);
            return text;
        }
    }
}

